"""
renderer/composite_videoref.py — Video-reference MuseTalk renderer.

Extends the single-image CompositeRenderer with a **bank of reference frames**
sampled from a source video (e.g., a 10-25s portrait clip of the subject).

Why this matters
----------------
A single PNG portrait produces a talking head that looks "frozen" — no blinks,
no micro-motion, no natural skin-texture variance. The face region is
regenerated by MuseTalk, but the shoulders/hair/background are bit-identical
across the whole output.

Feeding MuseTalk a short video of the subject sitting still and blinking
naturally gives us:
  * Real blinks and subtle head sway from the source, preserved in the output
  * Natural skin-texture variance frame-to-frame (no "plastic" feel)
  * A richer set of face latents to re-generate the mouth from — each frame's
    mouth/jaw shape becomes a different baseline, which helps audio-driven
    inference look more natural

How it works
------------
On init:
  1. Open the video with cv2.VideoCapture (or ffmpeg if cv2 fails)
  2. Uniformly sample `num_ref_frames` frames across the clip's duration
  3. Each sampled frame is:
       - kept at native resolution as an RGB frame in `portrait_rgb_bank`
       - cropped to the face bbox + margin, resized to 256×256, VAE-encoded →
         stashed in `face_latents_bank`

On render_frame(features, frame_index=t):
  1. bank_idx = t % N (cycle through reference frames)
  2. MuseTalk inference uses `face_latents_bank[bank_idx]` as the conditioning
     latents (instead of a single fixed tensor)
  3. The generated mouth is composited back into
     `portrait_rgb_bank[bank_idx]` (not a fixed portrait), so the output
     preserves the source video's blinks, micro-motion, and texture variance

Cache key
---------
The server caches renderers by portrait identity + bbox + params, same as the
single-image path. A video-ref renderer is keyed on the source video URL + a
`video_ref::` prefix so it never clashes with a still-portrait renderer for
the same subject.
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Optional, Sequence

import numpy as np

from .engine import AudioFeatures

logger = logging.getLogger(__name__)

_VENDOR_DIR = Path(__file__).parent / "muse_talk_vendor"


class MuseTalkVideoRefRenderer:
    """
    Video-reference MuseTalk renderer. See module docstring.

    Parameters
    ----------
    video_path : str
        Path to the source reference video (any ffmpeg-readable format).
    face_box : (x1, y1, x2, y2)
        Face bounding box, in the video's pixel coordinates. Assumed stable
        across the clip (i.e., the subject sat still while filming). We use
        the same bbox for every sampled frame.
    num_ref_frames : int
        How many reference frames to sample from the video.
        Default 60 — ~2-3s of 25fps motion before the bank loops.
        Higher = more variety, more VRAM, slower warm-up.
        Lower = more obvious looping.
    (rest match MuseTalkCompositeRenderer)
    """

    def __init__(
        self,
        video_path: str,
        face_box: Sequence[int],
        *,
        device: str = "cuda",
        model_dir: str | Path,
        use_float16: bool = True,
        extra_margin: int = 10,
        parsing_mode: str = "jaw",
        left_cheek_width: int = 90,
        right_cheek_width: int = 90,
        use_gfpgan: bool = False,
        gfpgan_weight: float = 0.5,
        num_ref_frames: int = 60,
    ) -> None:
        import cv2
        import torch

        self.device = device
        self.use_float16 = use_float16
        self.weight_dtype = torch.float16 if use_float16 else torch.float32
        self.model_dir = Path(model_dir)
        self.extra_margin = int(extra_margin)
        self.parsing_mode = parsing_mode
        self.num_ref_frames = int(num_ref_frames)

        vendor_str = str(_VENDOR_DIR)
        if vendor_str not in sys.path:
            sys.path.insert(0, vendor_str)

        # Load video → sample N frames uniformly across its duration
        frames_bgr = self._sample_video_frames(video_path, self.num_ref_frames)
        self.portrait_rgb_bank: list[np.ndarray] = [
            cv2.cvtColor(f, cv2.COLOR_BGR2RGB) for f in frames_bgr
        ]
        self.portrait_h, self.portrait_w = self.portrait_rgb_bank[0].shape[:2]
        logger.info(
            "VideoRefRenderer: loaded %d reference frames at %dx%d from %s",
            len(self.portrait_rgb_bank), self.portrait_w, self.portrait_h, video_path,
        )

        # Clamp bbox + apply extra margin. Same bbox is assumed to apply to
        # every sampled frame (static-subject assumption). If the subject
        # wobbles visibly during the clip, caller should pick a tighter bbox
        # or re-run bbox detection per frame (not done here).
        x1, y1, x2, y2 = (int(v) for v in face_box)
        x1 = max(0, x1)
        y1 = max(0, y1)
        x2 = min(self.portrait_w, x2)
        y2 = min(self.portrait_h, y2 + self.extra_margin)
        if x2 <= x1 or y2 <= y1:
            raise ValueError(f"Invalid face_box after clamp: {(x1,y1,x2,y2)}")
        self.bbox = (x1, y1, x2, y2)

        logger.info(
            "VideoRefRenderer: portrait=%dx%d bbox=%s (extra_margin=%d) parsing_mode=%s",
            self.portrait_w, self.portrait_h, self.bbox, self.extra_margin, parsing_mode,
        )

        self._load_models()
        self._init_face_parser(
            left_cheek_width=left_cheek_width,
            right_cheek_width=right_cheek_width,
        )
        self._precompute_face_latents_bank()

        self.sharpener = None
        if use_gfpgan:
            from .gfpgan_pass import GFPGANSharpener  # noqa: PLC0415
            self.sharpener = GFPGANSharpener(
                model_dir=self.model_dir,
                device=device,
                weight=gfpgan_weight,
            )
            logger.info(
                "VideoRefRenderer: GFPGAN post-pass ENABLED (weight=%.2f)", gfpgan_weight,
            )
        else:
            logger.info("VideoRefRenderer: GFPGAN post-pass disabled.")

    # ------------------------------------------------------------------ frames
    def _sample_video_frames(self, video_path: str, n: int) -> list[np.ndarray]:
        """Sample ``n`` frames uniformly across the clip duration.

        Returns a list of BGR frames as numpy uint8.
        Falls back to ffmpeg if cv2 can't decode (HEVC 10-bit on some builds).
        """
        import cv2  # noqa: PLC0415

        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened():
            logger.warning("cv2 couldn't open %s, falling back to ffmpeg", video_path)
            return self._sample_via_ffmpeg(video_path, n)

        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        if total < 1:
            cap.release()
            logger.warning("cv2 reported %d frames for %s, falling back to ffmpeg", total, video_path)
            return self._sample_via_ffmpeg(video_path, n)

        logger.info(
            "cv2 opened %s: total=%d fps=%.2f dur=%.2fs",
            video_path, total, fps, total / fps,
        )

        # Take `n` samples evenly spaced between [total*0.05, total*0.95]
        # (trim 5% off each end to avoid fade-in/fade-out artefacts).
        lo = max(0, int(total * 0.05))
        hi = max(lo + 1, int(total * 0.95))
        if n >= (hi - lo):
            idxs = list(range(lo, hi))
        else:
            idxs = [int(lo + (hi - lo) * i / (n - 1)) for i in range(n)]

        frames: list[np.ndarray] = []
        for idx in idxs:
            cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
            ok, frame = cap.read()
            if not ok or frame is None:
                logger.warning("cv2 read failed at frame %d, skipping", idx)
                continue
            frames.append(frame)

        cap.release()

        if len(frames) < 2:
            logger.warning(
                "cv2 returned %d usable frames, falling back to ffmpeg", len(frames),
            )
            return self._sample_via_ffmpeg(video_path, n)

        return frames

    def _sample_via_ffmpeg(self, video_path: str, n: int) -> list[np.ndarray]:
        """Fallback sampler — decode via ffmpeg, pick n frames, return BGR."""
        import cv2  # noqa: PLC0415

        # Probe duration
        probe = subprocess.run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", video_path],
            check=True, capture_output=True, text=True,
        )
        dur = float(probe.stdout.strip())
        logger.info("ffmpeg duration probe: %.2fs", dur)

        # Sample at uniform timestamps
        tstamps = [dur * (0.05 + 0.9 * i / max(1, n - 1)) for i in range(n)]
        tmp_dir = Path("/tmp") / f"videoref-{os.getpid()}"
        tmp_dir.mkdir(parents=True, exist_ok=True)

        frames: list[np.ndarray] = []
        for i, t in enumerate(tstamps):
            out = tmp_dir / f"frame-{i:04d}.png"
            subprocess.run(
                ["ffmpeg", "-y", "-ss", f"{t:.3f}", "-i", video_path,
                 "-frames:v", "1", str(out)],
                check=True, capture_output=True,
            )
            img = cv2.imread(str(out))
            if img is not None:
                frames.append(img)
            out.unlink(missing_ok=True)

        try:
            tmp_dir.rmdir()
        except OSError:
            pass

        if len(frames) < 2:
            raise RuntimeError(f"ffmpeg fallback returned only {len(frames)} frames from {video_path}")
        return frames

    # ------------------------------------------------------------------ models
    def _load_models(self) -> None:
        import torch  # noqa: PLC0415
        from musetalk.utils.utils import load_all_model  # noqa: PLC0415
        from transformers import WhisperModel  # noqa: PLC0415

        unet_path = str(self.model_dir / "musetalkV15" / "unet.pth")
        unet_config = str(self.model_dir / "musetalkV15" / "musetalk.json")

        logger.info("Loading MuseTalk models from %s …", self.model_dir)
        self.vae, self.unet, self.pe = load_all_model(
            unet_model_path=unet_path,
            vae_type="sd-vae",
            unet_config=unet_config,
            device=self.device,
        )

        whisper_path = str(self.model_dir / "whisper")
        logger.info("Loading Whisper encoder from %s …", whisper_path)
        self.whisper = WhisperModel.from_pretrained(whisper_path)
        self.whisper.to(self.device).to(self.weight_dtype).eval()

        self.vae.vae.to(self.device, dtype=self.weight_dtype)
        self.unet.model.to(self.device, dtype=self.weight_dtype)
        self.pe.to(self.device, dtype=self.weight_dtype)

        logger.info("MuseTalk models on %s (fp16=%s)", self.device, self.use_float16)

    # ------------------------------------------------------------------ face parser
    def _init_face_parser(self, *, left_cheek_width: int, right_cheek_width: int) -> None:
        from musetalk.utils.face_parsing import FaceParsing  # noqa: PLC0415

        workspace_root = Path(__file__).resolve().parents[1]
        models_link = workspace_root / "models"
        if not models_link.exists():
            try:
                os.symlink(str(self.model_dir), str(models_link))
            except OSError as e:
                logger.warning("Could not symlink %s: %s", models_link, e)

        old_cwd = os.getcwd()
        try:
            if Path(old_cwd) != workspace_root:
                os.chdir(str(workspace_root))
            self.face_parser = FaceParsing(
                left_cheek_width=left_cheek_width,
                right_cheek_width=right_cheek_width,
            )
        finally:
            if Path(old_cwd) != workspace_root:
                os.chdir(old_cwd)

    # ------------------------------------------------------------------ latents
    def _precompute_face_latents_bank(self) -> None:
        """For each reference frame, crop the face region and VAE-encode it."""
        import cv2  # noqa: PLC0415
        import torch  # noqa: PLC0415

        x1, y1, x2, y2 = self.bbox
        self._face_crop_shape = (y2 - y1, x2 - x1)

        self.face_latents_bank: list = []
        with torch.no_grad():
            for i, rgb in enumerate(self.portrait_rgb_bank):
                face_crop = rgb[y1:y2, x1:x2]
                face_256 = cv2.resize(face_crop, (256, 256), interpolation=cv2.INTER_LANCZOS4)
                latents = self.vae.get_latents_for_unet(face_256).to(dtype=self.weight_dtype)
                self.face_latents_bank.append(latents)
        logger.info(
            "Face latents bank: %d entries, each shape %s",
            len(self.face_latents_bank),
            tuple(self.face_latents_bank[0].shape),
        )

    # ------------------------------------------------------------------ warm-up
    def warm_up(self) -> None:
        import torch  # noqa: PLC0415

        logger.info("Warming up VideoRef GPU kernels …")
        dummy = torch.zeros(1, 50, 384, device=self.device, dtype=self.weight_dtype)
        dummy_features = AudioFeatures(whisper_features=dummy.cpu().numpy())
        self.render_frame(dummy_features, frame_index=0)
        logger.info("Warm-up complete.")

    # ------------------------------------------------------------------ render
    def render_frame(self, audio_features: AudioFeatures, frame_index: int = 0) -> np.ndarray:
        """Render one output frame using reference frame at (frame_index % N)."""
        import cv2  # noqa: PLC0415
        import torch  # noqa: PLC0415
        from musetalk.utils.blending import get_image  # noqa: PLC0415

        bank_idx = frame_index % len(self.face_latents_bank)
        face_latents = self.face_latents_bank[bank_idx]
        portrait_rgb = self.portrait_rgb_bank[bank_idx]

        x1, y1, x2, y2 = self.bbox

        whisper_slice = audio_features.whisper_features[frame_index : frame_index + 1]
        audio_tensor = torch.from_numpy(whisper_slice).to(self.device, dtype=self.weight_dtype)
        audio_prompt = self.pe(audio_tensor)
        timesteps = torch.zeros(1, device=self.device, dtype=torch.long)

        with torch.no_grad():
            pred_latents = self.unet.model(
                face_latents,
                timesteps,
                encoder_hidden_states=audio_prompt,
            ).sample
            recon = self.vae.decode_latents(pred_latents)

        if hasattr(recon, "__len__") and len(recon) > 0 and recon.ndim == 4:
            res_256 = recon[0]
        else:
            res_256 = recon
        res_uint8 = np.clip(res_256, 0, 255).astype(np.uint8)

        if self.sharpener is not None:
            res_uint8 = self.sharpener.enhance(res_uint8)

        h_crop, w_crop = self._face_crop_shape
        res_orig = cv2.resize(res_uint8, (w_crop, h_crop), interpolation=cv2.INTER_LANCZOS4)

        combined = get_image(
            portrait_rgb,  # ← uses THIS bank frame as the background
            res_orig,
            [x1, y1, x2, y2],
            mode=self.parsing_mode,
            fp=self.face_parser,
        )
        return combined
